export const WELCOME_MESSAGES = [
  "Welcome! I’m your AI assistant, ready to help you move faster and think smarter.",
  "Hello! I’m here to support your workflow — just tell me what you need.",
  "Greetings. Your AI agent is online and fully operational.",
  "Welcome aboard. Let’s turn your ideas into results.",
  "Hello! I’m here to simplify your tasks and amplify your productivity.",
  "Hey there! Great to see you — how can I help today?",
  "Hi! I’m your AI companion. Let’s make something awesome together.",
  "Welcome! I’m here to make your day a little easier.",
  "Hello! Ready when you are — just say the word.",
  "Hey! I’m online and excited to help you out.",
  "Let’s go! Your AI agent is fired up and ready to assist.",
  "Welcome! Time to get things done — I’ve got your back.",
  "You’re in! Let’s build, create, and solve together.",
  "Ready to roll! What challenge are we tackling first?",
  "Let’s make progress happen — I’m here and fully charged.",
  "System online. AI agent initialized. Awaiting your command.",
  "Neural core activated. How may I assist?",
  "Welcome, operator. Your AI system is standing by.",
  "Connection established. Ready to process your next request.",
  "AI module booted successfully. What’s our mission?",
  "Hey! Your friendly neighborhood AI has arrived.",
  "Ta‑da! I’m here — what’s the plan?",
  "Boop! AI agent activated. Let’s do cool things.",
  "Hi! I promise I’m smarter than I look. What’s up?",
  "Welcome! I’m 0% human, 100% ready to help.",

]